/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.recordedlectures.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Lecture service. Represents a row in the &quot;RL_Lecture&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.recordedlectures.model.impl.LectureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.recordedlectures.model.impl.LectureImpl</code>.
 * </p>
 *
 * @author liferay
 * @see Lecture
 * @generated
 */
@ProviderType
public interface LectureModel
	extends BaseModel<Lecture>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lecture model instance should use the {@link Lecture} interface instead.
	 */

	/**
	 * Returns the primary key of this lecture.
	 *
	 * @return the primary key of this lecture
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lecture.
	 *
	 * @param primaryKey the primary key of this lecture
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this lecture.
	 *
	 * @return the mvcc version of this lecture
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this lecture.
	 *
	 * @param mvccVersion the mvcc version of this lecture
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this lecture.
	 *
	 * @return the uuid of this lecture
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this lecture.
	 *
	 * @param uuid the uuid of this lecture
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the recordedlecture ID of this lecture.
	 *
	 * @return the recordedlecture ID of this lecture
	 */
	public long getRecordedlectureId();

	/**
	 * Sets the recordedlecture ID of this lecture.
	 *
	 * @param recordedlectureId the recordedlecture ID of this lecture
	 */
	public void setRecordedlectureId(long recordedlectureId);

	/**
	 * Returns the title of this lecture.
	 *
	 * @return the title of this lecture
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this lecture.
	 *
	 * @param Title the title of this lecture
	 */
	public void setTitle(String Title);

	/**
	 * Returns the video url of this lecture.
	 *
	 * @return the video url of this lecture
	 */
	@AutoEscape
	public String getVideoURL();

	/**
	 * Sets the video url of this lecture.
	 *
	 * @param videoURL the video url of this lecture
	 */
	public void setVideoURL(String videoURL);

	/**
	 * Returns the group ID of this lecture.
	 *
	 * @return the group ID of this lecture
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lecture.
	 *
	 * @param groupId the group ID of this lecture
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this lecture.
	 *
	 * @return the company ID of this lecture
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lecture.
	 *
	 * @param companyId the company ID of this lecture
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this lecture.
	 *
	 * @return the user ID of this lecture
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lecture.
	 *
	 * @param userId the user ID of this lecture
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lecture.
	 *
	 * @return the user uuid of this lecture
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lecture.
	 *
	 * @param userUuid the user uuid of this lecture
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lecture.
	 *
	 * @return the user name of this lecture
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lecture.
	 *
	 * @param userName the user name of this lecture
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lecture.
	 *
	 * @return the create date of this lecture
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lecture.
	 *
	 * @param createDate the create date of this lecture
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lecture.
	 *
	 * @return the modified date of this lecture
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lecture.
	 *
	 * @param modifiedDate the modified date of this lecture
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this lecture.
	 *
	 * @return the status of this lecture
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this lecture.
	 *
	 * @param status the status of this lecture
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this lecture.
	 *
	 * @return the status by user ID of this lecture
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this lecture.
	 *
	 * @param statusByUserId the status by user ID of this lecture
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this lecture.
	 *
	 * @return the status by user uuid of this lecture
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this lecture.
	 *
	 * @param statusByUserUuid the status by user uuid of this lecture
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this lecture.
	 *
	 * @return the status by user name of this lecture
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this lecture.
	 *
	 * @param statusByUserName the status by user name of this lecture
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this lecture.
	 *
	 * @return the status date of this lecture
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this lecture.
	 *
	 * @param statusDate the status date of this lecture
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this lecture is approved.
	 *
	 * @return <code>true</code> if this lecture is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this lecture is denied.
	 *
	 * @return <code>true</code> if this lecture is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this lecture is a draft.
	 *
	 * @return <code>true</code> if this lecture is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this lecture is expired.
	 *
	 * @return <code>true</code> if this lecture is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this lecture is inactive.
	 *
	 * @return <code>true</code> if this lecture is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this lecture is incomplete.
	 *
	 * @return <code>true</code> if this lecture is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this lecture is pending.
	 *
	 * @return <code>true</code> if this lecture is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this lecture is scheduled.
	 *
	 * @return <code>true</code> if this lecture is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public Lecture cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}